# Generated by Django 4.0 on 2021-12-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_company_logo_alter_specialty_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_original_id',
            field=models.IntegerField(null=True),
        ),
    ]
