# Generated by Django 4.0 on 2022-01-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_company_company_original_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_original_id',
        ),
    ]
