# Generated by Django 4.0 on 2022-01-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_company_owner_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='height_field',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='company',
            name='width_field',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='specialty',
            name='height_field',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='specialty',
            name='width_field',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(height_field='height_field', upload_to='company_images', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(height_field='height_field', upload_to='speciality_images', width_field='width_field'),
        ),
    ]
