# Generated by Django 4.0 on 2022-01-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_company_height_field_company_width_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='height_field',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_max',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_min',
            field=models.PositiveIntegerField(),
        ),
    ]
